name: Build OpenGCC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build-OpenGCC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Compiler
        run: sudo apt-get install -y gcc-arm-none-eabi
      - name: Create Build Directory
        run: mkdir ${{ github.workspace }}/build
      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE:STRING=Release -B ${{ github.workspace }}/build  
      - name: Build
        run: cmake --build ${{ github.workspace }}/build
  